### ISSUE TITLE
Morfeusz is unavailable

### ISSUE THREAD

**Issue by lambdaofgod** [ipipan/spacy-pl#10]
Morfeusz site is dead: http://morfeusz.sgjp.pl/ gives
> 
> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request
> 
> Reason: DNS lookup failure for: morfeuszwww.lxd
> 
> Apache/2.4.29 (Ubuntu) Server at morfeusz.sgjp.pl Port 80

Can you host files needed to run spacy with Morfeusz?

**Comment by ryszardtuora** [comment]
We're not really responsible for Morfeusz, so I can't help with the webpage itself, but it appears that downloading files is still possible.

If you're working on Ubuntu, please try the following:

`!wget -O - http://download.sgjp.pl/apt/sgjp.gpg.key|sudo apt-key add -`
`!sudo apt-add-repository http://download.sgjp.pl/apt/ubuntu`
`!sudo apt update`
`!sudo apt install morfeusz2`
`!sudo apt install python3-morfeusz2`

to install Morfeusz.
