### ISSUE TITLE
0.0.5 update

### ISSUE THREAD

**Issue by ryszardtuora** [ipipan/spacy-pl#3]
### 0.0.5 update

Today we've released a new version which cumulates some improvements we've developed in October. These include:
-From now on, our model is available on the GNU GPL 3.0 license.
-NER no longer splits forenames and surnames into different entities, the f1 score for entities is now 88.13.
-Parser now correctly splits documents into sentences, it is no longer necessary to do it by hand in order for parser to work right.
-Parser is now using the PDB treebank, which is more than twice as big as LFG which was used previously.

Additionally, we've made public our second version of the model, which utilizes Morfeusz 2 library
You can download them from [here](http://zil.ipipan.waw.pl/SpacyPL)

The evaluation metrics are available ![here](https://github.com/ipipan/spacy-pl/tree/master/evaluation/eval005.png)

Plans for the future:
-We are now working towards having our model endorsed by explosion.ai as an officially supported model for Polish.
-Further improvements to our parser - the model we're working with now, is still not satisfying. However this will likely require fixing some bugs within spaCy itself.
-Creating a custom component for sentiment analysis for our pipeline.
-Tagging with extended tags (i.e. morphological features such as case, grammatical gender or tense)

Please, do experiment with it, and let us know about your results!

**Comment by kuchenrolle** [comment]
Are the evaluation scores you report comparable to the state-of-the-art scores that Wróblewska and Rybak (2019, "Dependency Parsing of Polish") report using the Stanford parser (https://github.com/tdozat/Parser-v2)? They report an F1 of 88.88 for LAS on PDB (91.7 for UAS), which your results (88.1/91.1) get quite close to - is that comparison correct or are you using the gold-standard tokenization/lemmas/POS to evaluate the parser (for which the sota scores rise to 90.61/92.78)?

The new version with Morfeusz now splits agglutinative verb forms (e.g. "nabrała") into two tokens ("nabrał" + "a"). Can I savely merge every base with its aux:clitic dependent? (Maybe that could even be added as an attribute.)

**Comment by ryszardtuora** [comment]
I'll look into the article when I get access to it, and try to give a more informed answer. Right now I cannot reach the exact evaluation script theyve used, so I cannot be certain, but they do claim [here](http://clip.ipipan.waw.pl/benchmarks) that it was based on `conll18_ud_eval.py` which I've used to get the results. In any case, the parser in spaCy uses exclusively word vectors as input, and we run it on pure text, so I believe our results should be compared to the 91.70/88.88 metric.

I've tried running some sentences through the model, and just as I recalled, `'nabrała'` was not split into `'nabrał'` and `'a'`. Could you provide an example of a full sentence? Maybe our versions of Morfeusz2 differ. 

In any case we dont split off all the suffixes from verbs, but only those which can be moved around the sentence naturally. E.g. 'Woleliby' can be replaced by 'Oni by woleli', or 'Woleliśmy' by 'Myśmy woleli'. We will add an option to turn this off in a new version, but because all the training resources follow this way of segmentation, we might expect some drop of accuracy for other components of the pipeline.

You can merge two tokens via doc.merge(start_offset, end_offset) method. aux:clitic (or aglt tag, or dependencies beginning with aug for that matter) would not work for all cases though, as 'by' infix or suffix is usually labeled as part aux:cnd, also sometimes we split verbs into three tokens, and one of them might not be labeled with aux:clitic. Here's example of conllu output from our module:

> 1	Woleli	woleć	VERB	praet	_	0	root	_	_
> 2	by	by:q	PART	part	_	1	aux:cnd	_	_
> 3	śmy	być	AUX	aglt	_	1	aux:clitic	_	_
> 4	zrobić	zrobić	VERB	inf	_	1	xcomp	_	_
> 5	to	to	NOUN	subst	_	4	obj	_	_
> 6	osobiście	osobiście	ADV	adv	_	4	advmod	_	_
> 

Merging will make the new token inherit all the annotations (except for the lemma) from the head token (`Woleli`).
