### ISSUE TITLE
No information about spaCy version required

### ISSUE THREAD

**Issue by maciejbiesek** [ipipan/spacy-pl#4]
I installed your model of spaCy using command
`pip install "http://zil.ipipan.waw.pl/SpacyPL?action=AttachFile&do=get&target=pl_spacy_model-0.0.5.tar.gz"` and when I tried to use `spacy.load("pl_spacy_model")` I got 
`ModuleNotFoundError: No module named 'spacy.lookups'` exception. The problem disappeared after upgrading spaCy from 2.1.9 to 2.2.3.

**Comment by ryszardtuora** [comment]
Thank you for the tip!
We've updated our readme.

**Comment by maciejbiesek** [comment]
Thanks. ;)
